# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

name: mining

dependencies:
  - python=3.7.6

  - psutil=5.6 #latest

  - numpy=1.18.1
  - pandas=1.0.0
  - scikit-learn=0.22.1

  - pip=19.2.3
  - pip:
      - azureml-core==1.0.85
      - azureml-defaults==1.0.85
      - inference-schema[numpy-support]==1.0.1
      - azureml-dataprep==1.1.38
      - azure
      - python-dotenv
      - azure-cli-core
      - azure-storage
      - azure-storage-blob